# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Swift

on: [push]

jobs:
  build:
    name: Swift on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v2
        if: startsWith(matrix.os, 'ubuntu')
        with:
          swift-version: "6"
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
        if: startsWith(matrix.os, 'macos')
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libjemalloc-dev
        if: startsWith(matrix.os, 'ubuntu')
      - name: Resolve Swift package dependencies
        run: swift package resolve
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
